export const month6TraineeWorkoutPlan = {
  meta: {
    generatedDate: '2024-05-21',
    programType: '6-Month Transformation',
    targetTimeline: '6 Months',
    totalWeeks: 24,
  },
  workoutPlan: [
    {
      weekNumber: 1,
      focus: 'Month 1: Adaptation - Introduction',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Bodyweight squats, pushups, lunges (3 sets of 10).',
          durationMinutes: 45,
          caloriesBurned: 300,
          intensity: 'Low-Medium',
        },
        {
          day: 2,
          workoutType: 'Cardio LISS',
          description: 'Brisk walking or light cycling.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Full Body Strength',
          description: 'Dumbbell rows, overhead press, planks.',
          durationMinutes: 45,
          caloriesBurned: 320,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Rest & Stretch',
          description: 'Light stretching.',
          durationMinutes: 15,
          caloriesBurned: 50,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Full Body Circuit',
          description: 'Circuit style: Jumping jacks, squats, burpees.',
          durationMinutes: 30,
          caloriesBurned: 350,
          intensity: 'Medium-High',
        },
        {
          day: 6,
          workoutType: 'Active Lifestyle',
          description: 'Hiking or long walk.',
          durationMinutes: 60,
          caloriesBurned: 300,
          intensity: 'Low',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Complete Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 2,
      focus: 'Month 1: Adaptation - Consistency',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Increase reps to 12. Focus on form.',
          durationMinutes: 50,
          caloriesBurned: 330,
          intensity: 'Medium',
        },
        {
          day: 2,
          workoutType: 'Cardio LISS',
          description: 'Incline walking.',
          durationMinutes: 35,
          caloriesBurned: 250,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Upper Body Focus',
          description: 'Push and Pull movements.',
          durationMinutes: 45,
          caloriesBurned: 310,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Core & Mobility',
          description: 'Yoga for flexibility.',
          durationMinutes: 30,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Lower Body Focus',
          description: 'Lunges, Squats, Calf raises.',
          durationMinutes: 45,
          caloriesBurned: 360,
          intensity: 'Medium-High',
        },
        {
          day: 6,
          workoutType: 'Cardio Intervals',
          description: 'Jog 2 mins, Walk 2 mins.',
          durationMinutes: 30,
          caloriesBurned: 280,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Complete Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 3,
      focus: 'Month 1: Adaptation - Intensity',
      schedule: [
        {
          day: 1,
          workoutType: 'Upper Body Strength',
          description: 'Chest press, rows, shoulder press.',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Lower Body Strength',
          description: 'Goblet squats, deadlifts.',
          durationMinutes: 50,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Cardio HIIT',
          description: '30 sec sprint, 30 sec rest.',
          durationMinutes: 25,
          caloriesBurned: 300,
          intensity: 'High',
        },
        {
          day: 4,
          workoutType: 'Active Recovery',
          description: 'Swimming or easy cycle.',
          durationMinutes: 40,
          caloriesBurned: 250,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Full Body Compound',
          description: 'Big movements: Squat, Pushup, Row.',
          durationMinutes: 55,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Endurance Cardio',
          description: 'Steady state run.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Foam rolling.',
          durationMinutes: 20,
          caloriesBurned: 80,
          intensity: 'Low',
        },
      ],
    },
    {
      weekNumber: 4,
      focus: 'Month 1: Deload & Technique',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Light',
          description: 'Reduce weight by 50%, perfect technique.',
          durationMinutes: 40,
          caloriesBurned: 250,
          intensity: 'Low-Medium',
        },
        {
          day: 2,
          workoutType: 'Mobility Flow',
          description: 'Deep stretching and joint health.',
          durationMinutes: 30,
          caloriesBurned: 120,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Bodyweight Circuit',
          description: 'Flow movement, animal flow.',
          durationMinutes: 35,
          caloriesBurned: 220,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Rest',
          description: 'Complete Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 5,
          workoutType: 'Cardio LISS',
          description: 'Easy bike ride.',
          durationMinutes: 40,
          caloriesBurned: 250,
          intensity: 'Low',
        },
        {
          day: 6,
          workoutType: 'Core Stability',
          description: 'Planks and deadbugs.',
          durationMinutes: 25,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Mental reset.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 5,
      focus: 'Month 2: Hypertrophy - Building Muscle',
      schedule: [
        {
          day: 1,
          workoutType: 'Push Day',
          description: 'Chest, Shoulders, Triceps (3x10-12).',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Pull Day',
          description: 'Back, Biceps, Rear Delts (3x10-12).',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Legs Day',
          description: 'Quads, Hams, Glutes (3x10-12).',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 4,
          workoutType: 'Cardio LISS',
          description: 'Recovery run.',
          durationMinutes: 30,
          caloriesBurned: 280,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Upper Body Pump',
          description: 'High reps (15-20) upper body.',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'Medium-High',
        },
        {
          day: 6,
          workoutType: 'Lower Body Pump',
          description: 'High reps (15-20) lower body.',
          durationMinutes: 45,
          caloriesBurned: 380,
          intensity: 'Medium-High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 6,
      focus: 'Month 2: Hypertrophy - Increasing Volume',
      schedule: [
        {
          day: 1,
          workoutType: 'Push Day',
          description: 'Add 1 set to compound lifts.',
          durationMinutes: 65,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Pull Day',
          description: 'Add 1 set to compound lifts.',
          durationMinutes: 65,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'HIIT Cardio',
          description: 'Tabata Protocol (4 mins hard).',
          durationMinutes: 20,
          caloriesBurned: 250,
          intensity: 'Very High',
        },
        {
          day: 4,
          workoutType: 'Legs Day',
          description: 'Add 1 set to squats.',
          durationMinutes: 65,
          caloriesBurned: 480,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Core & Abs',
          description: 'Weighted ab work.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Full Body Metcon',
          description: 'Metabolic conditioning.',
          durationMinutes: 40,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 7,
      focus: 'Month 2: Hypertrophy - Peak Volume',
      schedule: [
        {
          day: 1,
          workoutType: 'Push Day',
          description: 'Drop sets on final set.',
          durationMinutes: 70,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Pull Day',
          description: 'Drop sets on final set.',
          durationMinutes: 70,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Steady State Cardio',
          description: 'Moderate intensity row or run.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Legs Day',
          description: 'Supersets for legs.',
          durationMinutes: 70,
          caloriesBurned: 500,
          intensity: 'Very High',
        },
        {
          day: 5,
          workoutType: 'Arm Farm',
          description: 'Biceps and Triceps isolation.',
          durationMinutes: 45,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Outdoor Activity',
          description: 'Sport or hiking.',
          durationMinutes: 90,
          caloriesBurned: 600,
          intensity: 'Variable',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Massage or Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 8,
      focus: 'Month 2: Active Recovery',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Mobility',
          description: 'Dynamic stretching routine.',
          durationMinutes: 40,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 2,
          workoutType: 'Light Cardio',
          description: 'Walking.',
          durationMinutes: 45,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Yoga',
          description: 'Vinyasa flow.',
          durationMinutes: 45,
          caloriesBurned: 180,
          intensity: 'Low-Medium',
        },
        {
          day: 4,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 5,
          workoutType: 'Bodyweight Technique',
          description: 'Practice form with no weight.',
          durationMinutes: 30,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 6,
          workoutType: 'Light Swim',
          description: 'Casual laps.',
          durationMinutes: 30,
          caloriesBurned: 220,
          intensity: 'Low',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Prepare for Strength Phase.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 9,
      focus: 'Month 3: Strength - Heavy Lifting',
      schedule: [
        {
          day: 1,
          workoutType: 'Heavy Upper',
          description: '5 sets of 5 reps (Bench/Row).',
          durationMinutes: 60,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Heavy Lower',
          description: '5 sets of 5 reps (Squat/Deadlift).',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Rest',
          description: 'CNS Recovery.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 4,
          workoutType: 'Hypertrophy Accessory',
          description: 'Supporting muscle groups (3x10).',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'Medium',
        },
        {
          day: 5,
          workoutType: 'HIIT Sprints',
          description: 'Track sprints or bike sprints.',
          durationMinutes: 25,
          caloriesBurned: 300,
          intensity: 'Very High',
        },
        {
          day: 6,
          workoutType: 'Full Body Power',
          description: 'Explosive movements (cleans, jumps).',
          durationMinutes: 45,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 10,
      focus: 'Month 3: Strength - Max Intensity',
      schedule: [
        {
          day: 1,
          workoutType: 'Max Effort Upper',
          description: 'Build to heavy triple (3 reps).',
          durationMinutes: 65,
          caloriesBurned: 410,
          intensity: 'Very High',
        },
        {
          day: 2,
          workoutType: 'Max Effort Lower',
          description: 'Build to heavy triple (3 reps).',
          durationMinutes: 65,
          caloriesBurned: 460,
          intensity: 'Very High',
        },
        {
          day: 3,
          workoutType: 'Active Recovery',
          description: 'Walking or Yoga.',
          durationMinutes: 30,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Core & GPP',
          description: 'General Physical Preparedness circuit.',
          durationMinutes: 40,
          caloriesBurned: 300,
          intensity: 'Medium-High',
        },
        {
          day: 5,
          workoutType: 'Speed Work',
          description: 'Lighter weights moved fast (Dynamic effort).',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'Medium-High',
        },
        {
          day: 6,
          workoutType: 'Long Cardio',
          description: 'Zone 2 training (Run/Bike).',
          durationMinutes: 60,
          caloriesBurned: 500,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Deep Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 11,
      focus: 'Month 3: Performance Peaking',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Maintain heavy weight, reduce volume (3x3).',
          durationMinutes: 55,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Anaerobic Conditioning',
          description: 'Hard intervals (1 min on, 2 min off).',
          durationMinutes: 30,
          caloriesBurned: 320,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Mobility & Prehab',
          description: 'Rotator cuff and hip work.',
          durationMinutes: 40,
          caloriesBurned: 180,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Full Body Strength',
          description: 'Focus on Squat and Press.',
          durationMinutes: 55,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Plyometrics',
          description: 'Box jumps and bounding.',
          durationMinutes: 30,
          caloriesBurned: 250,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Cross-Training',
          description: 'Pick a new sport/activity.',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'Variable',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 12,
      focus: 'Month 3: Final Test & Deload',
      schedule: [
        {
          day: 1,
          workoutType: 'Testing Day 1',
          description: 'Test 1RM or max reps for Upper Body.',
          durationMinutes: 50,
          caloriesBurned: 300,
          intensity: 'Very High',
        },
        {
          day: 2,
          workoutType: 'Rest',
          description: 'Recovery.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 3,
          workoutType: 'Testing Day 2',
          description: 'Test 1RM or max reps for Lower Body.',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'Very High',
        },
        {
          day: 4,
          workoutType: 'Cardio Test',
          description: 'Timed run (1 mile or 5k).',
          durationMinutes: 30,
          caloriesBurned: 300,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Celebration Workout',
          description: 'Fun full body pump.',
          durationMinutes: 40,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Mobility',
          description: 'Long stretch session.',
          durationMinutes: 40,
          caloriesBurned: 120,
          intensity: 'Low',
        },
        {
          day: 7,
          workoutType: 'Reflection',
          description: 'Plan next 3 months.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 13,
      focus: 'Month 4: Metabolic Conditioning - Density',
      schedule: [
        {
          day: 1,
          workoutType: 'Upper Body Density',
          description: 'Supersets with minimal rest (Chest/Back).',
          durationMinutes: 45,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Lower Body Density',
          description: 'Tri-sets (Squat/Lunge/Calf).',
          durationMinutes: 50,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Cardio Intervals',
          description: '1 min fast / 1 min slow x 15.',
          durationMinutes: 30,
          caloriesBurned: 300,
          intensity: 'High',
        },
        {
          day: 4,
          workoutType: 'Active Recovery',
          description: 'Light cycle.',
          durationMinutes: 40,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Full Body Circuit',
          description: '5 exercises, 4 rounds, no rest.',
          durationMinutes: 40,
          caloriesBurned: 400,
          intensity: 'Very High',
        },
        {
          day: 6,
          workoutType: 'Steady State Run',
          description: '5km moderate pace.',
          durationMinutes: 35,
          caloriesBurned: 350,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Complete Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 14,
      focus: 'Month 4: Metabolic Conditioning - Endurance',
      schedule: [
        {
          day: 1,
          workoutType: 'Push Endurance',
          description: 'High rep ranges (15-20 reps).',
          durationMinutes: 50,
          caloriesBurned: 360,
          intensity: 'Medium-High',
        },
        {
          day: 2,
          workoutType: 'Pull Endurance',
          description: 'High rep ranges (15-20 reps).',
          durationMinutes: 50,
          caloriesBurned: 360,
          intensity: 'Medium-High',
        },
        {
          day: 3,
          workoutType: 'HIIT',
          description: 'Tabata sprints on bike.',
          durationMinutes: 25,
          caloriesBurned: 280,
          intensity: 'Very High',
        },
        {
          day: 4,
          workoutType: 'Legs Endurance',
          description: 'High volume lunges and step-ups.',
          durationMinutes: 55,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Core Blaster',
          description: 'Obliques and rectus abdominis focus.',
          durationMinutes: 25,
          caloriesBurned: 150,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Outdoor Hike/Ruck',
          description: 'Walk with weighted backpack.',
          durationMinutes: 60,
          caloriesBurned: 500,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 15,
      focus: 'Month 4: Metabolic Conditioning - Peak Heart Rate',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body EMOM',
          description: 'Every Minute On the Minute lifts.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'Very High',
        },
        {
          day: 2,
          workoutType: 'LISS Cardio',
          description: 'Zone 2 recovery run.',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Upper Body Strength',
          description: 'Maintain strength (3x8).',
          durationMinutes: 45,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Mobility Flow',
          description: 'Yoga for hips.',
          durationMinutes: 30,
          caloriesBurned: 100,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Lower Body Strength',
          description: 'Maintain strength (3x8).',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Sprint Intervals',
          description: 'Track sprints or hill sprints.',
          durationMinutes: 30,
          caloriesBurned: 320,
          intensity: 'Very High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Epsom salt bath.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 16,
      focus: 'Month 4: Deload & Mobility',
      schedule: [
        {
          day: 1,
          workoutType: 'Bodyweight Flow',
          description: 'Move through ranges of motion.',
          durationMinutes: 30,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 2,
          workoutType: 'Light Cardio',
          description: 'Brisk walk.',
          durationMinutes: 40,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Core Stability',
          description: 'Pilates style session.',
          durationMinutes: 30,
          caloriesBurned: 120,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 5,
          workoutType: 'Technique Day',
          description: 'Practice Olympic lift form (PVC pipe).',
          durationMinutes: 30,
          caloriesBurned: 100,
          intensity: 'Low',
        },
        {
          day: 6,
          workoutType: 'Fun Activity',
          description: 'Swimming or Dance.',
          durationMinutes: 40,
          caloriesBurned: 250,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Prep for Power Phase.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 17,
      focus: 'Month 5: Functional Power - Explosiveness',
      schedule: [
        {
          day: 1,
          workoutType: 'Power Upper',
          description: 'Clapping pushups, Med ball slams.',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Power Lower',
          description: 'Jump squats, Kettlebell swings.',
          durationMinutes: 50,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Cardio Recovery',
          description: 'Elliptical.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Athletic Full Body',
          description: 'Landmine presses, sled pushes.',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'Very High',
        },
        {
          day: 5,
          workoutType: 'Core & Rotation',
          description: 'Russian twists, woodchoppers.',
          durationMinutes: 30,
          caloriesBurned: 180,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Agility Drills',
          description: 'Ladder drills, cone drills.',
          durationMinutes: 40,
          caloriesBurned: 300,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 18,
      focus: 'Month 5: Functional Power - Complex Training',
      schedule: [
        {
          day: 1,
          workoutType: 'Contrast Training',
          description: 'Heavy squat paired with box jump.',
          durationMinutes: 55,
          caloriesBurned: 420,
          intensity: 'Very High',
        },
        {
          day: 2,
          workoutType: 'Contrast Training',
          description: 'Heavy bench paired with med ball throw.',
          durationMinutes: 55,
          caloriesBurned: 380,
          intensity: 'Very High',
        },
        {
          day: 3,
          workoutType: 'Active Recovery',
          description: 'Yoga.',
          durationMinutes: 40,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Unilateral Strength',
          description: 'Single leg RDL, Bulgarian split squats.',
          durationMinutes: 50,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Pull Power',
          description: 'Pendlay rows, High pulls.',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Long Cardio',
          description: 'Run or Row (10km / 5km).',
          durationMinutes: 50,
          caloriesBurned: 450,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 19,
      focus: 'Month 5: Functional Power - Strength Endurance',
      schedule: [
        {
          day: 1,
          workoutType: 'Kettlebell Flow',
          description: 'Turkish getups, snatches.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Bodyweight Power',
          description: 'Muscle-up progression or dips.',
          durationMinutes: 45,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 3,
          workoutType: 'Sprints',
          description: 'Short max effort sprints.',
          durationMinutes: 20,
          caloriesBurned: 250,
          intensity: 'Very High',
        },
        {
          day: 4,
          workoutType: 'Functional Circuit',
          description: 'Farmer carries, sandbag work.',
          durationMinutes: 50,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Mobility',
          description: 'Animal flow.',
          durationMinutes: 30,
          caloriesBurned: 150,
          intensity: 'Low',
        },
        {
          day: 6,
          workoutType: 'Sports Day',
          description: 'Tennis, Basketball, Soccer.',
          durationMinutes: 60,
          caloriesBurned: 500,
          intensity: 'Variable',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 20,
      focus: 'Month 5: Mini-Deload',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Pump',
          description: 'Light weight, continuous tension.',
          durationMinutes: 35,
          caloriesBurned: 250,
          intensity: 'Low',
        },
        {
          day: 2,
          workoutType: 'Walking',
          description: 'Nature walk.',
          durationMinutes: 45,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Core Focus',
          description: 'Abs and lower back.',
          durationMinutes: 25,
          caloriesBurned: 100,
          intensity: 'Low',
        },
        {
          day: 4,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 5,
          workoutType: 'Swimming',
          description: 'Easy laps.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 6,
          workoutType: 'Stretching',
          description: 'Full body static stretch.',
          durationMinutes: 30,
          caloriesBurned: 80,
          intensity: 'Low',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Mental Prep for Final Month.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 21,
      focus: 'Month 6: Advanced Aesthetic - Split Routine',
      schedule: [
        {
          day: 1,
          workoutType: 'Chest & Calves',
          description: 'Focus on upper chest development.',
          durationMinutes: 60,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Back & Abs',
          description: 'Width and thickness for back.',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'LISS Cardio',
          description: 'Fasted walking (optional) or steady jog.',
          durationMinutes: 40,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Shoulders & Traps',
          description: 'Overhead pressing and lateral raises.',
          durationMinutes: 55,
          caloriesBurned: 320,
          intensity: 'High',
        },
        {
          day: 5,
          workoutType: 'Legs',
          description: 'Heavy compound leg day.',
          durationMinutes: 70,
          caloriesBurned: 500,
          intensity: 'Very High',
        },
        {
          day: 6,
          workoutType: 'Arms (Bi/Tri)',
          description: 'Super sets for arms.',
          durationMinutes: 45,
          caloriesBurned: 300,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 22,
      focus: 'Month 6: Advanced Aesthetic - Weak Points',
      schedule: [
        {
          day: 1,
          workoutType: 'Legs (Quad Focus)',
          description: 'Front squats, leg extensions.',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Push (Chest/Delt)',
          description: 'Focus on pressing strength.',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Pull (Back/Rear Delt)',
          description: 'Row variations.',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 4,
          workoutType: 'HIIT',
          description: 'Rowing machine intervals.',
          durationMinutes: 20,
          caloriesBurned: 250,
          intensity: 'Very High',
        },
        {
          day: 5,
          workoutType: 'Legs (Glute/Ham)',
          description: 'RDLs, Hip thrusts.',
          durationMinutes: 60,
          caloriesBurned: 420,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Upper Body Pump',
          description: 'High volume everything.',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 23,
      focus: 'Month 6: Advanced Aesthetic - Refining',
      schedule: [
        {
          day: 1,
          workoutType: 'Upper Body Strength',
          description: 'Maintenance volume, high weight.',
          durationMinutes: 50,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Lower Body Strength',
          description: 'Maintenance volume, high weight.',
          durationMinutes: 50,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Cardio',
          description: 'Steady state run.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Full Body Hypertrophy',
          description: 'Machines focus (stabilization).',
          durationMinutes: 60,
          caloriesBurned: 380,
          intensity: 'Medium',
        },
        {
          day: 5,
          workoutType: 'Core & Cardio',
          description: 'Ab circuit + 20 min run.',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Full Body Circuit',
          description: 'Depletion workout.',
          durationMinutes: 45,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest',
          description: 'Rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 24,
      focus: 'Month 6: Final Peak & Assessment',
      schedule: [
        {
          day: 1,
          workoutType: 'Testing: Squat',
          description: 'Test 1RM Squat.',
          durationMinutes: 40,
          caloriesBurned: 200,
          intensity: 'Max',
        },
        {
          day: 2,
          workoutType: 'Testing: Bench',
          description: 'Test 1RM Bench Press.',
          durationMinutes: 40,
          caloriesBurned: 180,
          intensity: 'Max',
        },
        {
          day: 3,
          workoutType: 'Rest',
          description: 'Recovery.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 4,
          workoutType: 'Testing: Deadlift',
          description: 'Test 1RM Deadlift.',
          durationMinutes: 40,
          caloriesBurned: 250,
          intensity: 'Max',
        },
        {
          day: 5,
          workoutType: 'Testing: Run',
          description: 'Test 5k time or 1 mile time.',
          durationMinutes: 30,
          caloriesBurned: 300,
          intensity: 'Max',
        },
        {
          day: 6,
          workoutType: 'Victory Lap',
          description: 'Your favorite workout.',
          durationMinutes: 60,
          caloriesBurned: 400,
          intensity: 'Fun',
        },
        {
          day: 7,
          workoutType: '6-Month Review',
          description: 'Plan next 6 months.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
  ],
  dietaryPlan: [
    {
      weekNumber: 1,
      focus: 'Adaptation Phase',
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oatmeal with berries',
            lunch: 'Grilled chicken salad',
            dinner: 'Salmon and quinoa',
            snack: 'Yogurt',
          },
          totalCalories: 2150,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Scrambled eggs on toast',
            lunch: 'Turkey wrap',
            dinner: 'Beef stir-fry',
            snack: 'Apple',
          },
          totalCalories: 2200,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Protein smoothie',
            lunch: 'Tuna sandwich',
            dinner: 'Grilled tofu and veggies',
            snack: 'Nuts',
          },
          totalCalories: 2180,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Avocado toast',
            lunch: 'Chicken Caesar salad',
            dinner: 'Cod fish tacos',
            snack: 'Protein bar',
          },
          totalCalories: 2210,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Greek yogurt parfait',
            lunch: 'Lentil soup',
            dinner: 'Steak and potatoes',
            snack: 'Cottage cheese',
          },
          totalCalories: 2250,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Whole wheat pancakes',
            lunch: 'Shrimp salad',
            dinner: 'Pasta primavera',
            snack: 'Boiled eggs',
          },
          totalCalories: 2230,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Veggie omelet',
            lunch: 'Leftover pasta',
            dinner: 'Roast chicken',
            snack: 'Dark chocolate',
          },
          totalCalories: 2150,
        },
      ],
    },
    {
      weekNumber: 2,
      focus: 'Adaptation Phase',
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Chia pudding',
            lunch: 'Burrito bowl',
            dinner: 'Turkey meatballs',
            snack: 'Rice cake',
          },
          totalCalories: 2180,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Egg white frittata',
            lunch: 'Grilled cheese & soup',
            dinner: 'Pork tenderloin',
            snack: 'Orange',
          },
          totalCalories: 2220,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Protein waffles',
            lunch: 'Salmon sandwich',
            dinner: 'Vegetarian chili',
            snack: 'Shake',
          },
          totalCalories: 2150,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Bagel and lox',
            lunch: 'Chicken skewers',
            dinner: 'Stuffed peppers',
            snack: 'Pear',
          },
          totalCalories: 2190,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Breakfast burrito',
            lunch: 'Quinoa salad',
            dinner: 'Grilled tilapia',
            snack: 'Jerky',
          },
          totalCalories: 2210,
        },
        {
          day: 6,
          meals: {
            breakfast: 'French toast',
            lunch: 'Roast beef wrap',
            dinner: 'Homemade pizza',
            snack: 'Popcorn',
          },
          totalCalories: 2350,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Smoothie bowl',
            lunch: 'Minestrone soup',
            dinner: 'BBQ Chicken',
            snack: 'Grapes',
          },
          totalCalories: 2100,
        },
      ],
    },
    {
      weekNumber: 3,
      focus: 'Adaptation Phase',
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'PB & Banana Oats',
            lunch: 'Chicken & roasted veg',
            dinner: 'Shrimp stir fry',
            snack: 'Greek yogurt',
          },
          totalCalories: 2250,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Tofu scramble',
            lunch: 'Cobb salad',
            dinner: 'Lemon herb chicken',
            snack: 'Almonds',
          },
          totalCalories: 2230,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Muesli',
            lunch: 'Bison burger (lettuce wrap)',
            dinner: 'Baked cod',
            snack: 'Hummus',
          },
          totalCalories: 2260,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Eggs benedict (light)',
            lunch: 'Sushi roll',
            dinner: 'Chicken parmesan',
            snack: 'Fruit salad',
          },
          totalCalories: 2280,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Green smoothie',
            lunch: 'Turkey sandwich',
            dinner: 'Lamb chops',
            snack: 'Cheese stick',
          },
          totalCalories: 2240,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Blueberry pancakes',
            lunch: 'Chicken noodle soup',
            dinner: 'Steak fajitas',
            snack: 'Trail mix',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Granola',
            lunch: 'Fajita salad',
            dinner: 'Eggplant parm',
            snack: 'Banana',
          },
          totalCalories: 2150,
        },
      ],
    },
    {
      weekNumber: 4,
      focus: 'Deload & Maintenance',
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Rye toast & cottage cheese',
            lunch: 'Grilled chicken',
            dinner: 'Salmon cakes',
            snack: 'Kiwi',
          },
          totalCalories: 2180,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Boiled eggs',
            lunch: 'Asian salad',
            dinner: 'Beef stew',
            snack: 'Yogurt',
          },
          totalCalories: 2210,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Choco smoothie',
            lunch: 'Quesadilla',
            dinner: 'Halibut',
            snack: 'Pretzels',
          },
          totalCalories: 2200,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Overnight oats',
            lunch: 'Ham sandwich',
            dinner: 'Veggie curry',
            snack: 'Apricots',
          },
          totalCalories: 2190,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Salmon scramble',
            lunch: 'Clam chowder',
            dinner: 'Meatloaf',
            snack: 'Celery & PB',
          },
          totalCalories: 2250,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Waffles',
            lunch: 'Club sandwich',
            dinner: 'Mushroom risotto',
            snack: 'Chocolate',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'English breakfast',
            lunch: 'Shrimp Caesar',
            dinner: 'Roast pork',
            snack: 'Ice cream',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 5,
      focus: 'Hypertrophy Surplus',
      dailyIntakeGoal: 2500,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Large Omelet (3 eggs)',
            lunch: 'Chicken pasta',
            dinner: 'Steak and rice',
            snack: 'Protein shake & banana',
          },
          totalCalories: 2500,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Oats with extra PB',
            lunch: 'Turkey chili',
            dinner: 'Salmon & sweet potato',
            snack: 'Greek yogurt & granola',
          },
          totalCalories: 2480,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Bagel sandwich',
            lunch: 'Beef burrito',
            dinner: 'Chicken curry',
            snack: 'Nuts & jerky',
          },
          totalCalories: 2550,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Smoothie (High cal)',
            lunch: 'Tuna melt',
            dinner: 'Pork chops & mash',
            snack: 'Cheese & crackers',
          },
          totalCalories: 2450,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Pancakes & eggs',
            lunch: 'Meatball sub',
            dinner: 'Fish & chips (baked)',
            snack: 'Protein bar',
          },
          totalCalories: 2520,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Breakfast skillet',
            lunch: 'Chicken burger',
            dinner: 'Spaghetti bolognese',
            snack: 'Milk & cookies',
          },
          totalCalories: 2600,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Avocado toast with bacon',
            lunch: 'Leftover spaghetti',
            dinner: 'Roast beef dinner',
            snack: 'Fruit smoothie',
          },
          totalCalories: 2400,
        },
      ],
    },
    {
      weekNumber: 6,
      focus: 'Hypertrophy Surplus',
      dailyIntakeGoal: 2500,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Scrambled eggs & hashbrowns',
            lunch: 'Chicken rice bowl',
            dinner: 'Beef tacos',
            snack: 'Apple with PB',
          },
          totalCalories: 2500,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Overnight oats (large)',
            lunch: 'Turkey club',
            dinner: 'Shrimp alfredo',
            snack: 'Yogurt',
          },
          totalCalories: 2480,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Breakfast wrap',
            lunch: 'Lentil stew',
            dinner: 'Grilled salmon',
            snack: 'Protein shake',
          },
          totalCalories: 2520,
        },
        {
          day: 4,
          meals: {
            breakfast: 'French toast',
            lunch: 'Steak salad',
            dinner: 'Chicken enchiladas',
            snack: 'Trail mix',
          },
          totalCalories: 2550,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Yogurt bowl',
            lunch: 'Pulled pork sandwich',
            dinner: 'Burger (no bun)',
            snack: 'Cottage cheese',
          },
          totalCalories: 2490,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Waffles',
            lunch: 'Sushi',
            dinner: 'Pizza (2 slices)',
            snack: 'Popcorn',
          },
          totalCalories: 2600,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Eggs benedict',
            lunch: 'Soup & sandwich',
            dinner: 'Ribs & corn',
            snack: 'Berries',
          },
          totalCalories: 2450,
        },
      ],
    },
    {
      weekNumber: 7,
      focus: 'Hypertrophy Surplus',
      dailyIntakeGoal: 2550,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Protein pancakes',
            lunch: 'Chicken pesto pasta',
            dinner: 'Steak & asparagus',
            snack: 'Shake',
          },
          totalCalories: 2550,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Oatmeal & walnuts',
            lunch: 'Turkey burger',
            dinner: 'Baked ziti',
            snack: 'Hummus & pita',
          },
          totalCalories: 2520,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Egg & cheese bagel',
            lunch: 'Beef stir fry',
            dinner: 'Salmon tacos',
            snack: 'Fruit',
          },
          totalCalories: 2580,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Smoothie bowl',
            lunch: 'Chicken wrap',
            dinner: 'Meatloaf',
            snack: 'Bar',
          },
          totalCalories: 2500,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Frittata',
            lunch: 'Tuna pasta salad',
            dinner: 'Lamb curry',
            snack: 'Cheese',
          },
          totalCalories: 2540,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Full breakfast',
            lunch: 'Philly cheesesteak',
            dinner: 'Crab cakes',
            snack: 'Nuts',
          },
          totalCalories: 2650,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Crepes',
            lunch: 'Cobb salad',
            dinner: 'Roast chicken',
            snack: 'Chocolate',
          },
          totalCalories: 2480,
        },
      ],
    },
    {
      weekNumber: 8,
      focus: 'Recovery Phase',
      dailyIntakeGoal: 2300,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Light oatmeal',
            lunch: 'Grilled chicken salad',
            dinner: 'White fish & veg',
            snack: 'Yogurt',
          },
          totalCalories: 2300,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Scrambled eggs',
            lunch: 'Veggie wrap',
            dinner: 'Turkey stir fry',
            snack: 'Apple',
          },
          totalCalories: 2280,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Smoothie',
            lunch: 'Minestrone',
            dinner: 'Shrimp scampi (zucchini noodles)',
            snack: 'Almonds',
          },
          totalCalories: 2250,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Toast & PB',
            lunch: 'Tuna salad',
            dinner: 'Chicken breast',
            snack: 'Pear',
          },
          totalCalories: 2290,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Yogurt parfait',
            lunch: 'Sushi (light)',
            dinner: 'Tofu curry',
            snack: 'Rice cake',
          },
          totalCalories: 2310,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Poached eggs',
            lunch: 'Soup & salad',
            dinner: 'Beef kebabs',
            snack: 'Berries',
          },
          totalCalories: 2350,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Omelet',
            lunch: 'Leftover kebabs',
            dinner: 'Roast pork',
            snack: 'Tea & biscuit',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 9,
      focus: 'Performance Fuel',
      dailyIntakeGoal: 2350,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Egg & Turkey Bacon',
            lunch: 'Quinoa & Shrimp',
            dinner: 'Sirloin Steak',
            snack: 'Protein Shake',
          },
          totalCalories: 2350,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Greek Yogurt & Seeds',
            lunch: 'Chicken Pita',
            dinner: 'Salmon & Rice',
            snack: 'Apple & Almonds',
          },
          totalCalories: 2320,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Spinach Smoothie',
            lunch: 'Lentil Soup',
            dinner: 'Turkey Meatloaf',
            snack: 'Cottage Cheese',
          },
          totalCalories: 2340,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Chia Oats',
            lunch: 'Tuna Salad',
            dinner: 'Veggie Stir-fry',
            snack: 'Boiled Eggs',
          },
          totalCalories: 2300,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Avocado Toast',
            lunch: 'Caesar Salad',
            dinner: 'Fish Tacos',
            snack: 'Protein Bar',
          },
          totalCalories: 2380,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Protein Pancakes',
            lunch: 'Turkey Burger',
            dinner: 'Whole Wheat Pasta',
            snack: 'Yogurt',
          },
          totalCalories: 2400,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Smoked Salmon Eggs',
            lunch: 'Leftover Pasta',
            dinner: 'Roast Chicken',
            snack: 'Dark Chocolate',
          },
          totalCalories: 2300,
        },
      ],
    },
    {
      weekNumber: 10,
      focus: 'Performance Fuel',
      dailyIntakeGoal: 2350,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Breakfast Burrito',
            lunch: 'Chicken & Sprouts',
            dinner: 'Bison Steak',
            snack: 'Rice Cake & PB',
          },
          totalCalories: 2380,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Overnight Oats',
            lunch: 'Turkey Sandwich',
            dinner: 'Shrimp Scampi',
            snack: 'Orange',
          },
          totalCalories: 2320,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Mango Chia Pudding',
            lunch: 'Cobb Salad',
            dinner: 'Pork Tenderloin',
            snack: 'Cheese String',
          },
          totalCalories: 2300,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Tofu Scramble',
            lunch: 'Grilled Cheese',
            dinner: 'Chicken Curry',
            snack: 'Pear',
          },
          totalCalories: 2340,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Bagel & Cream Cheese',
            lunch: 'Sushi Roll',
            dinner: 'Swordfish',
            snack: 'Jerky',
          },
          totalCalories: 2360,
        },
        {
          day: 6,
          meals: {
            breakfast: 'French Toast',
            lunch: 'Roast Beef Wrap',
            dinner: 'Pizza (Veggie)',
            snack: 'Popcorn',
          },
          totalCalories: 2400,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Smoothie Bowl',
            lunch: 'Minestrone',
            dinner: 'BBQ Chicken',
            snack: 'Grapes',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 11,
      focus: 'Performance Fuel',
      dailyIntakeGoal: 2350,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oats & Walnuts',
            lunch: 'Chicken Stir Fry',
            dinner: 'Salmon Burger',
            snack: 'Parfait',
          },
          totalCalories: 2350,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Eggs & Sausage',
            lunch: 'Hummus Plate',
            dinner: 'Spaghetti Squash',
            snack: 'Shake',
          },
          totalCalories: 2320,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Muesli',
            lunch: 'Salmon Sandwich',
            dinner: 'Steak Salad',
            snack: 'Nuts',
          },
          totalCalories: 2380,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Poached Eggs',
            lunch: 'Chicken Soup',
            dinner: 'Cod & Rice',
            snack: 'Banana',
          },
          totalCalories: 2300,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Berry Smoothie',
            lunch: 'Turkey Club',
            dinner: 'Lamb Kebab',
            snack: 'Cheese',
          },
          totalCalories: 2340,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Waffles',
            lunch: 'Fajita Bowl',
            dinner: 'Eggplant Parm',
            snack: 'Fruit',
          },
          totalCalories: 2390,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Granola',
            lunch: 'Leftover Fajitas',
            dinner: 'Duck Breast',
            snack: 'Chocolate',
          },
          totalCalories: 2300,
        },
      ],
    },
    {
      weekNumber: 12,
      focus: 'Deload & Maintenance',
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Toast & Almond Butter',
            lunch: 'Grilled Chicken',
            dinner: 'Baked Tilapia',
            snack: 'Kiwi',
          },
          totalCalories: 2200,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Boiled Eggs',
            lunch: 'Asian Salad',
            dinner: 'Beef Stew',
            snack: 'Yogurt',
          },
          totalCalories: 2250,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Choco Smoothie',
            lunch: 'Quesadilla',
            dinner: 'Halibut',
            snack: 'Pretzels',
          },
          totalCalories: 2220,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Overnight Oats',
            lunch: 'Ham Sandwich',
            dinner: 'Veggie Curry',
            snack: 'Apricots',
          },
          totalCalories: 2240,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Scrambled Eggs',
            lunch: 'Clam Chowder',
            dinner: 'Turkey Meatloaf',
            snack: 'Celery & PB',
          },
          totalCalories: 2260,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Pancakes',
            lunch: 'Club Sandwich',
            dinner: 'Risotto',
            snack: 'Cookie',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Full English (Light)',
            lunch: 'Shrimp Caesar',
            dinner: 'Roast Pork',
            snack: 'Berries',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 13,
      focus: 'Metabolic Fuel',
      dailyIntakeGoal: 2400,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oatmeal with whey protein',
            lunch: 'Chicken & rice bowl',
            dinner: 'Lean beef stir-fry',
            snack: 'Greek yogurt',
          },
          totalCalories: 2400,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Scrambled eggs & toast',
            lunch: 'Turkey wrap',
            dinner: 'Salmon & quinoa',
            snack: 'Banana & almonds',
          },
          totalCalories: 2380,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Smoothie (Berries/Spinach)',
            lunch: 'Tuna pasta salad',
            dinner: 'Grilled chicken & veg',
            snack: 'Rice cakes',
          },
          totalCalories: 2420,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Avocado toast with egg',
            lunch: 'Lentil soup',
            dinner: 'Cod fish tacos',
            snack: 'Protein bar',
          },
          totalCalories: 2350,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Greek yogurt bowl',
            lunch: 'Beef burger (no bun)',
            dinner: 'Shrimp curry',
            snack: 'Cottage cheese',
          },
          totalCalories: 2450,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Pancakes',
            lunch: 'Chicken Caesar salad',
            dinner: 'Pasta with meat sauce',
            snack: 'Hard boiled eggs',
          },
          totalCalories: 2500,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Veggie omelet',
            lunch: 'Leftover pasta',
            dinner: 'Roast pork',
            snack: 'Dark chocolate',
          },
          totalCalories: 2300,
        },
      ],
    },
    {
      weekNumber: 14,
      focus: 'Endurance Support',
      dailyIntakeGoal: 2450,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Bagel with cream cheese',
            lunch: 'Chicken burrito',
            dinner: 'Steak & sweet potato',
            snack: 'Shake',
          },
          totalCalories: 2450,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Eggs & turkey bacon',
            lunch: 'Quinoa salad',
            dinner: 'Baked ziti',
            snack: 'Apple',
          },
          totalCalories: 2420,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Chia pudding',
            lunch: 'Club sandwich',
            dinner: 'Tofu stir fry',
            snack: 'Nuts',
          },
          totalCalories: 2480,
        },
        {
          day: 4,
          meals: {
            breakfast: 'French toast',
            lunch: 'Soup & salad',
            dinner: 'Grilled tilapia',
            snack: 'Pear',
          },
          totalCalories: 2400,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Smoothie bowl',
            lunch: 'Sushi roll',
            dinner: 'Lamb chops',
            snack: 'Jerky',
          },
          totalCalories: 2500,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Waffles',
            lunch: 'Pizza (2 slices)',
            dinner: 'Chicken wings (baked)',
            snack: 'Popcorn',
          },
          totalCalories: 2550,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Granola',
            lunch: 'Cobb salad',
            dinner: 'Eggplant parmesan',
            snack: 'Berries',
          },
          totalCalories: 2350,
        },
      ],
    },
    {
      weekNumber: 15,
      focus: 'High Output Fuel',
      dailyIntakeGoal: 2450,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Protein porridge',
            lunch: 'Chicken & broccoli',
            dinner: 'Bison burger',
            snack: 'Yogurt',
          },
          totalCalories: 2450,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Egg white frittata',
            lunch: 'Turkey chili',
            dinner: 'Shrimp scampi',
            snack: 'Orange',
          },
          totalCalories: 2420,
        },
        {
          day: 3,
          meals: {
            breakfast: 'PB toast',
            lunch: 'Salmon salad',
            dinner: 'Chicken fajitas',
            snack: 'Almonds',
          },
          totalCalories: 2480,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Overnight oats',
            lunch: 'Ham sandwich',
            dinner: 'Pork tenderloin',
            snack: 'Banana',
          },
          totalCalories: 2440,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Smoothie',
            lunch: 'Veggie burger',
            dinner: 'Steak salad',
            snack: 'Cheese',
          },
          totalCalories: 2460,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Pancakes',
            lunch: 'Tuna melt',
            dinner: 'Lasagna',
            snack: 'Fruit salad',
          },
          totalCalories: 2500,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Scrambled eggs',
            lunch: 'Leftover lasagna',
            dinner: 'Roast chicken',
            snack: 'Chocolate',
          },
          totalCalories: 2350,
        },
      ],
    },
    {
      weekNumber: 16,
      focus: 'Deload (Reduced Calorie)',
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Toast & jam',
            lunch: 'Grilled chicken',
            dinner: 'White fish',
            snack: 'Kiwi',
          },
          totalCalories: 2200,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Boiled eggs',
            lunch: 'Green salad',
            dinner: 'Lean beef stew',
            snack: 'Yogurt',
          },
          totalCalories: 2250,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Small smoothie',
            lunch: 'Half sandwich',
            dinner: 'Chicken breast',
            snack: 'Pretzels',
          },
          totalCalories: 2220,
        },
        {
          day: 4,
          meals: { breakfast: 'Oatmeal', lunch: 'Soup', dinner: 'Veggie curry', snack: 'Apricots' },
          totalCalories: 2240,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Scrambled tofu',
            lunch: 'Clam chowder',
            dinner: 'Turkey meatloaf',
            snack: 'Celery',
          },
          totalCalories: 2260,
        },
        {
          day: 6,
          meals: { breakfast: 'Cereal', lunch: 'Wrap', dinner: 'Risotto', snack: 'Cookie' },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'English breakfast',
            lunch: 'Shrimp salad',
            dinner: 'Pork chop',
            snack: 'Tea',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 17,
      focus: 'Power Phase (Carb Timing)',
      dailyIntakeGoal: 2500,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Large oatmeal',
            lunch: 'Pasta with chicken',
            dinner: 'Steak & potato',
            snack: 'Gatorade/Shake',
          },
          totalCalories: 2500,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Bagel sandwich',
            lunch: 'Rice & beans',
            dinner: 'Salmon',
            snack: 'Granola bar',
          },
          totalCalories: 2480,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Pancakes',
            lunch: 'Sub sandwich',
            dinner: 'Chicken stir fry',
            snack: 'Fruit',
          },
          totalCalories: 2550,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Smoothie (High carb)',
            lunch: 'Burrito',
            dinner: 'Pork chops',
            snack: 'Pretzels',
          },
          totalCalories: 2450,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Waffles',
            lunch: 'Pizza (homemade)',
            dinner: 'Fish & chips',
            snack: 'Yogurt',
          },
          totalCalories: 2520,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Eggs & hashbrowns',
            lunch: 'Burger',
            dinner: 'Spaghetti',
            snack: 'Ice cream',
          },
          totalCalories: 2600,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Toast & avocado',
            lunch: 'Leftover pasta',
            dinner: 'Roast beef',
            snack: 'Berries',
          },
          totalCalories: 2400,
        },
      ],
    },
    {
      weekNumber: 18,
      focus: 'Power Phase (Carb Timing)',
      dailyIntakeGoal: 2500,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Omelet & toast',
            lunch: 'Chicken rice bowl',
            dinner: 'Beef tacos',
            snack: 'Apple',
          },
          totalCalories: 2500,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Overnight oats',
            lunch: 'Turkey club',
            dinner: 'Shrimp alfredo',
            snack: 'Yogurt',
          },
          totalCalories: 2480,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Breakfast wrap',
            lunch: 'Lentil stew',
            dinner: 'Grilled salmon',
            snack: 'Shake',
          },
          totalCalories: 2520,
        },
        {
          day: 4,
          meals: {
            breakfast: 'French toast',
            lunch: 'Steak salad',
            dinner: 'Enchiladas',
            snack: 'Trail mix',
          },
          totalCalories: 2550,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Yogurt bowl',
            lunch: 'Pulled pork',
            dinner: 'Burger',
            snack: 'Cheese',
          },
          totalCalories: 2490,
        },
        {
          day: 6,
          meals: { breakfast: 'Waffles', lunch: 'Sushi', dinner: 'Pizza', snack: 'Popcorn' },
          totalCalories: 2600,
        },
        {
          day: 7,
          meals: { breakfast: 'Eggs benedict', lunch: 'Soup', dinner: 'Ribs', snack: 'Grapes' },
          totalCalories: 2450,
        },
      ],
    },
    {
      weekNumber: 19,
      focus: 'Power Phase (Carb Timing)',
      dailyIntakeGoal: 2500,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Protein pancakes',
            lunch: 'Pesto pasta',
            dinner: 'Steak',
            snack: 'Shake',
          },
          totalCalories: 2500,
        },
        {
          day: 2,
          meals: { breakfast: 'Oatmeal', lunch: 'Turkey burger', dinner: 'Ziti', snack: 'Hummus' },
          totalCalories: 2480,
        },
        {
          day: 3,
          meals: { breakfast: 'Bagel', lunch: 'Stir fry', dinner: 'Fish tacos', snack: 'Fruit' },
          totalCalories: 2550,
        },
        {
          day: 4,
          meals: { breakfast: 'Smoothie', lunch: 'Wrap', dinner: 'Meatloaf', snack: 'Bar' },
          totalCalories: 2450,
        },
        {
          day: 5,
          meals: { breakfast: 'Frittata', lunch: 'Tuna salad', dinner: 'Curry', snack: 'Cheese' },
          totalCalories: 2520,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Full breakfast',
            lunch: 'Cheesesteak',
            dinner: 'Crab cakes',
            snack: 'Nuts',
          },
          totalCalories: 2600,
        },
        {
          day: 7,
          meals: { breakfast: 'Crepes', lunch: 'Salad', dinner: 'Chicken', snack: 'Chocolate' },
          totalCalories: 2400,
        },
      ],
    },
    {
      weekNumber: 20,
      focus: 'Mini-Deload',
      dailyIntakeGoal: 2300,
      days: [
        {
          day: 1,
          meals: { breakfast: 'Oats', lunch: 'Chicken salad', dinner: 'Tilapia', snack: 'Yogurt' },
          totalCalories: 2300,
        },
        {
          day: 2,
          meals: { breakfast: 'Eggs', lunch: 'Wrap', dinner: 'Turkey', snack: 'Apple' },
          totalCalories: 2280,
        },
        {
          day: 3,
          meals: { breakfast: 'Smoothie', lunch: 'Soup', dinner: 'Shrimp', snack: 'Almonds' },
          totalCalories: 2250,
        },
        {
          day: 4,
          meals: { breakfast: 'Toast', lunch: 'Tuna', dinner: 'Chicken', snack: 'Pear' },
          totalCalories: 2290,
        },
        {
          day: 5,
          meals: { breakfast: 'Parfait', lunch: 'Sushi', dinner: 'Tofu', snack: 'Rice cake' },
          totalCalories: 2310,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Poached eggs',
            lunch: 'Salad',
            dinner: 'Beef kebabs',
            snack: 'Berries',
          },
          totalCalories: 2350,
        },
        {
          day: 7,
          meals: { breakfast: 'Omelet', lunch: 'Leftovers', dinner: 'Pork', snack: 'Tea' },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 21,
      focus: 'Aesthetics (High Protein)',
      dailyIntakeGoal: 2300,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Egg whites & spinach',
            lunch: 'Chicken breast & rice',
            dinner: 'Lean steak & greens',
            snack: 'Protein shake',
          },
          totalCalories: 2300,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Greek yogurt',
            lunch: 'Turkey sandwich',
            dinner: 'Salmon & asparagus',
            snack: 'Almonds',
          },
          totalCalories: 2280,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Protein smoothie',
            lunch: 'Lentil soup',
            dinner: 'Turkey meatloaf',
            snack: 'Cottage cheese',
          },
          totalCalories: 2320,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Oats & chia',
            lunch: 'Tuna salad',
            dinner: 'Veggie stir fry',
            snack: 'Boiled eggs',
          },
          totalCalories: 2250,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Avocado toast',
            lunch: 'Caesar salad',
            dinner: 'White fish',
            snack: 'Bar',
          },
          totalCalories: 2350,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Pancakes',
            lunch: 'Burger (no bun)',
            dinner: 'Whole wheat pasta',
            snack: 'Yogurt',
          },
          totalCalories: 2380,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Smoked salmon',
            lunch: 'Leftover pasta',
            dinner: 'Roast chicken',
            snack: 'Chocolate',
          },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 22,
      focus: 'Aesthetics (Leaning Out)',
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: { breakfast: 'Burrito', lunch: 'Chicken', dinner: 'Bison', snack: 'Rice cake' },
          totalCalories: 2280,
        },
        {
          day: 2,
          meals: { breakfast: 'Oats', lunch: 'Turkey', dinner: 'Shrimp', snack: 'Orange' },
          totalCalories: 2220,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Chia pudding',
            lunch: 'Cobb salad',
            dinner: 'Pork',
            snack: 'Cheese',
          },
          totalCalories: 2250,
        },
        {
          day: 4,
          meals: { breakfast: 'Tofu', lunch: 'Grilled cheese', dinner: 'Curry', snack: 'Pear' },
          totalCalories: 2240,
        },
        {
          day: 5,
          meals: { breakfast: 'Bagel', lunch: 'Sushi', dinner: 'Swordfish', snack: 'Jerky' },
          totalCalories: 2260,
        },
        {
          day: 6,
          meals: { breakfast: 'French toast', lunch: 'Wrap', dinner: 'Pizza', snack: 'Popcorn' },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: { breakfast: 'Smoothie', lunch: 'Soup', dinner: 'Chicken', snack: 'Grapes' },
          totalCalories: 2200,
        },
      ],
    },
    {
      weekNumber: 23,
      focus: 'Aesthetics (Refining)',
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oats',
            lunch: 'Stir fry',
            dinner: 'Salmon burger',
            snack: 'Parfait',
          },
          totalCalories: 2250,
        },
        {
          day: 2,
          meals: { breakfast: 'Eggs', lunch: 'Hummus', dinner: 'Squash', snack: 'Shake' },
          totalCalories: 2220,
        },
        {
          day: 3,
          meals: { breakfast: 'Muesli', lunch: 'Salmon', dinner: 'Steak salad', snack: 'Nuts' },
          totalCalories: 2280,
        },
        {
          day: 4,
          meals: { breakfast: 'Poached eggs', lunch: 'Soup', dinner: 'Cod', snack: 'Banana' },
          totalCalories: 2200,
        },
        {
          day: 5,
          meals: { breakfast: 'Smoothie', lunch: 'Club', dinner: 'Lamb', snack: 'Cheese' },
          totalCalories: 2240,
        },
        {
          day: 6,
          meals: { breakfast: 'Waffles', lunch: 'Fajita', dinner: 'Eggplant', snack: 'Fruit' },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: { breakfast: 'Granola', lunch: 'Leftovers', dinner: 'Duck', snack: 'Chocolate' },
          totalCalories: 2250,
        },
      ],
    },
    {
      weekNumber: 24,
      focus: 'Peak Performance',
      dailyIntakeGoal: 2300,
      days: [
        {
          day: 1,
          meals: { breakfast: 'Toast', lunch: 'Chicken', dinner: 'Tilapia', snack: 'Kiwi' },
          totalCalories: 2300,
        },
        {
          day: 2,
          meals: { breakfast: 'Boiled eggs', lunch: 'Salad', dinner: 'Stew', snack: 'Yogurt' },
          totalCalories: 2280,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Smoothie',
            lunch: 'Quesadilla',
            dinner: 'Halibut',
            snack: 'Pretzels',
          },
          totalCalories: 2320,
        },
        {
          day: 4,
          meals: { breakfast: 'Oats', lunch: 'Sandwich', dinner: 'Curry', snack: 'Apricots' },
          totalCalories: 2300,
        },
        {
          day: 5,
          meals: { breakfast: 'Eggs', lunch: 'Chowder', dinner: 'Meatloaf', snack: 'Celery' },
          totalCalories: 2260,
        },
        {
          day: 6,
          meals: { breakfast: 'Pancakes', lunch: 'Club', dinner: 'Risotto', snack: 'Cookie' },
          totalCalories: 2350,
        },
        {
          day: 7,
          meals: { breakfast: 'Full English', lunch: 'Caesar', dinner: 'Pork', snack: 'Berries' },
          totalCalories: 2300,
        },
      ],
    },
  ],
}
