export const month1TraineeWorkoutPlan = {
  meta: {
    generatedDate: '2024-05-21',
    programType: 'Balanced Fitness & Health',
    targetTimeline: '1 Month',
  },
  workoutPlan: [
    {
      weekNumber: 1,
      focus: 'Adaptation & Form',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Compound movements focusing on form (Squats, Pushups, Rows).',
          durationMinutes: 45,
          caloriesBurned: 320,
          intensity: 'Medium',
        },
        {
          day: 2,
          workoutType: 'Cardio LISS',
          description: 'Low Intensity Steady State (Jogging or Cycling).',
          durationMinutes: 30,
          caloriesBurned: 250,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Upper Body Strength',
          description: 'Focus on chest, back, shoulders, and arms.',
          durationMinutes: 40,
          caloriesBurned: 280,
          intensity: 'Medium',
        },
        {
          day: 4,
          workoutType: 'Active Recovery / Yoga',
          description: 'Stretching and mobility work to aid recovery.',
          durationMinutes: 20,
          caloriesBurned: 100,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Lower Body Strength',
          description: 'Focus on quads, hamstrings, glutes, and calves.',
          durationMinutes: 45,
          caloriesBurned: 350,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Cardio HIIT',
          description: 'High Intensity Interval Training sprints.',
          durationMinutes: 25,
          caloriesBurned: 300,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest & Recovery',
          description: 'Complete rest. Hydration focus.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 2,
      focus: 'Increasing Intensity',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Increased weights or reps from Week 1.',
          durationMinutes: 50,
          caloriesBurned: 360,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Cardio LISS',
          description: 'Steady jogging or brisk incline walking.',
          durationMinutes: 35,
          caloriesBurned: 280,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Upper Body Hypertrophy',
          description: 'Higher reps for muscle endurance.',
          durationMinutes: 45,
          caloriesBurned: 310,
          intensity: 'Medium-High',
        },
        {
          day: 4,
          workoutType: 'Core & Abs',
          description: 'Planks, leg raises, and rotational strength.',
          durationMinutes: 20,
          caloriesBurned: 150,
          intensity: 'Medium',
        },
        {
          day: 5,
          workoutType: 'Lower Body Power',
          description: 'Explosive movements like jump squats and lunges.',
          durationMinutes: 45,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Cardio HIIT',
          description: 'Tabata style intervals.',
          durationMinutes: 30,
          caloriesBurned: 340,
          intensity: 'High',
        },
        {
          day: 7,
          workoutType: 'Rest & Recovery',
          description: 'Light walk or complete rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
    {
      weekNumber: 3,
      focus: 'Peak Volume',
      schedule: [
        {
          day: 1,
          workoutType: 'Push Day (Chest/Shoulders/Tri)',
          description: 'Push exercises focus.',
          durationMinutes: 55,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 2,
          workoutType: 'Pull Day (Back/Biceps)',
          description: 'Pull exercises focus.',
          durationMinutes: 55,
          caloriesBurned: 380,
          intensity: 'High',
        },
        {
          day: 3,
          workoutType: 'Legs & Glutes',
          description: 'Heavy compound leg movements.',
          durationMinutes: 60,
          caloriesBurned: 450,
          intensity: 'High',
        },
        {
          day: 4,
          workoutType: 'Active Recovery / Swimming',
          description: 'Low impact full body movement.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 5,
          workoutType: 'Full Body Circuit',
          description: 'High heart rate circuit training.',
          durationMinutes: 40,
          caloriesBurned: 400,
          intensity: 'High',
        },
        {
          day: 6,
          workoutType: 'Outdoor Cardio',
          description: 'Long run or hike.',
          durationMinutes: 60,
          caloriesBurned: 500,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest & Recovery',
          description: 'Foam rolling and stretching.',
          durationMinutes: 15,
          caloriesBurned: 50,
          intensity: 'Low',
        },
      ],
    },
    {
      weekNumber: 4,
      focus: 'Deload & Maintenance',
      schedule: [
        {
          day: 1,
          workoutType: 'Full Body Strength',
          description: 'Lighter weights, focus on perfect technique.',
          durationMinutes: 35,
          caloriesBurned: 250,
          intensity: 'Medium',
        },
        {
          day: 2,
          workoutType: 'Cardio LISS',
          description: 'Easy cycling or elliptical.',
          durationMinutes: 30,
          caloriesBurned: 200,
          intensity: 'Low',
        },
        {
          day: 3,
          workoutType: 'Pilates / Mobility',
          description: 'Core stability and flexibility.',
          durationMinutes: 40,
          caloriesBurned: 180,
          intensity: 'Low-Medium',
        },
        {
          day: 4,
          workoutType: 'Rest & Recovery',
          description: 'Complete rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
        {
          day: 5,
          workoutType: 'Bodyweight Flow',
          description: 'Bodyweight only exercises.',
          durationMinutes: 30,
          caloriesBurned: 220,
          intensity: 'Medium',
        },
        {
          day: 6,
          workoutType: 'Cardio Interval',
          description: 'Moderate intervals (1 min on, 1 min off).',
          durationMinutes: 25,
          caloriesBurned: 260,
          intensity: 'Medium',
        },
        {
          day: 7,
          workoutType: 'Rest & Reflection',
          description: 'Review progress and rest.',
          durationMinutes: 0,
          caloriesBurned: 0,
          intensity: 'None',
        },
      ],
    },
  ],
  dietaryPlan: [
    {
      weekNumber: 1,
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oatmeal with berries and protein powder',
            lunch: 'Grilled chicken breast with quinoa and steamed broccoli',
            dinner: 'Baked salmon with asparagus and sweet potato',
            snack: 'Greek yogurt with honey',
          },
          totalCalories: 2150,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Scrambled eggs (3) with spinach and whole wheat toast',
            lunch: 'Turkey wrap with hummus and mixed greens',
            dinner: 'Lean beef stir-fry with mixed vegetables and brown rice',
            snack: 'Apple slices with almond butter',
          },
          totalCalories: 2200,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Smoothie (Banana, Spinach, Protein, Almond Milk)',
            lunch: 'Tuna salad with light mayo and cucumber slices',
            dinner: 'Grilled tofu with roasted cauliflower and couscous',
            snack: 'Handful of mixed nuts',
          },
          totalCalories: 2100,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Avocado toast with poached egg',
            lunch: 'Chicken Caesar salad (light dressing)',
            dinner: 'Cod fish tacos with cabbage slaw',
            snack: 'Protein bar',
          },
          totalCalories: 2180,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Greek yogurt parfaits with granola',
            lunch: 'Lentil soup with a side of whole grain bread',
            dinner: 'Steak strips with bell peppers and mashed potatoes',
            snack: 'Cottage cheese with pineapple',
          },
          totalCalories: 2250,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Whole wheat pancakes with sugar-free syrup',
            lunch: 'Shrimp salad with avocado and lime dressing',
            dinner: 'Pasta primavera with whole wheat noodles',
            snack: 'Hard boiled eggs (2)',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Veggie omelet with cheese',
            lunch: 'Leftover pasta primavera with grilled chicken added',
            dinner: 'Roasted chicken thighs with green beans',
            snack: 'Dark chocolate square and berries',
          },
          totalCalories: 2150,
        },
      ],
    },
    {
      weekNumber: 2,
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Chia seed pudding with mango',
            lunch: 'Burrito bowl (Brown rice, black beans, chicken, salsa)',
            dinner: 'Turkey meatballs with zucchini noodles',
            snack: 'Rice cake with peanut butter',
          },
          totalCalories: 2180,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Egg white frittata with mushrooms',
            lunch: 'Grilled cheese on sourdough with tomato soup',
            dinner: 'Pork tenderloin with roasted brussels sprouts',
            snack: 'Orange and string cheese',
          },
          totalCalories: 2220,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Protein waffles',
            lunch: 'Salmon salad sandwich',
            dinner: 'Vegetarian chili with cornbread',
            snack: 'Protein shake',
          },
          totalCalories: 2150,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Bagel with light cream cheese and smoked salmon',
            lunch: 'Chicken and vegetable skewers',
            dinner: 'Stuffed bell peppers (ground turkey)',
            snack: 'Pear',
          },
          totalCalories: 2190,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Breakfast burrito (eggs, cheese, salsa)',
            lunch: 'Quinoa salad with chickpeas and feta',
            dinner: 'Grilled tilapia with wild rice',
            snack: 'Beef jerky',
          },
          totalCalories: 2210,
        },
        {
          day: 6,
          meals: {
            breakfast: 'French toast with strawberries',
            lunch: 'Roast beef wrap',
            dinner: 'Homemade pizza on whole wheat crust',
            snack: 'Popcorn (air popped)',
          },
          totalCalories: 2350,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Smoothie bowl',
            lunch: 'Minestrone soup',
            dinner: 'BBQ Chicken with corn on the cob',
            snack: 'Grapes',
          },
          totalCalories: 2100,
        },
      ],
    },
    {
      weekNumber: 3,
      dailyIntakeGoal: 2250,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Oatmeal with peanut butter and banana',
            lunch: 'Chicken breast with roasted root vegetables',
            dinner: 'Shrimp stir fry with snap peas',
            snack: 'Greek yogurt',
          },
          totalCalories: 2250,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Scrambled tofu with turmeric',
            lunch: 'Cobb salad',
            dinner: 'Lemon herb chicken with asparagus',
            snack: 'Almonds',
          },
          totalCalories: 2230,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Muesli with milk',
            lunch: 'Bison burger (no bun) with salad',
            dinner: 'Baked cod with kale salad',
            snack: 'Hummus and carrots',
          },
          totalCalories: 2260,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Eggs benedict (light hollandaise)',
            lunch: 'Sushi roll (California or Tuna) & Edamame',
            dinner: 'Chicken parmesan (baked) with side pasta',
            snack: 'Fruit salad',
          },
          totalCalories: 2280,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Smoothie (Berry and Kale)',
            lunch: 'Turkey sandwich on rye',
            dinner: 'Lamb chops with mint sauce and peas',
            snack: 'Cheese stick',
          },
          totalCalories: 2240,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Pancakes with blueberries',
            lunch: 'Chicken noodle soup',
            dinner: 'Fajitas (Chicken or Steak)',
            snack: 'Trail mix',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Granola with almond milk',
            lunch: 'Leftover fajitas made into a salad',
            dinner: 'Eggplant parmesan',
            snack: 'Banana',
          },
          totalCalories: 2150,
        },
      ],
    },
    {
      weekNumber: 4,
      dailyIntakeGoal: 2200,
      days: [
        {
          day: 1,
          meals: {
            breakfast: 'Rye toast with cottage cheese and tomato',
            lunch: 'Grilled chicken breast with sweet potato fries',
            dinner: 'Salmon cakes with green salad',
            snack: 'Kiwi fruit',
          },
          totalCalories: 2180,
        },
        {
          day: 2,
          meals: {
            breakfast: 'Boiled eggs and soldiers (toast strips)',
            lunch: 'Asian chicken salad',
            dinner: 'Beef stew with carrots and potatoes',
            snack: 'Yogurt',
          },
          totalCalories: 2210,
        },
        {
          day: 3,
          meals: {
            breakfast: 'Smoothie (Chocolate protein, spinach, PB)',
            lunch: 'Quesadilla with chicken and cheese',
            dinner: 'Halibut with lemon butter and rice',
            snack: 'Pretzels',
          },
          totalCalories: 2200,
        },
        {
          day: 4,
          meals: {
            breakfast: 'Overnight oats with apple and cinnamon',
            lunch: 'Ham and cheese sandwich',
            dinner: 'Vegetable curry with naan bread',
            snack: 'Dried apricots',
          },
          totalCalories: 2190,
        },
        {
          day: 5,
          meals: {
            breakfast: 'Scrambled eggs with smoked salmon',
            lunch: 'Clam chowder',
            dinner: 'Meatloaf with green beans',
            snack: 'Celery with peanut butter',
          },
          totalCalories: 2250,
        },
        {
          day: 6,
          meals: {
            breakfast: 'Waffles with fruit compote',
            lunch: 'Club sandwich',
            dinner: 'Risotto with mushrooms',
            snack: 'Dark chocolate',
          },
          totalCalories: 2300,
        },
        {
          day: 7,
          meals: {
            breakfast: 'Full English breakfast (light version)',
            lunch: 'Caesar salad with grilled shrimp',
            dinner: 'Roast pork with applesauce',
            snack: 'Ice cream (small scoop)',
          },
          totalCalories: 2250,
        },
      ],
    },
  ],
}
